#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	procd_open_instance "scheduler"
	procd_set_param command /bin/sh -c 'while true; do /usr/libexec/luci-sms-dataflow due; sleep 60; done'
	procd_set_param respawn 3600 5 5
	procd_close_instance
}
